notification.save.routingkey-name=apiclient.save.notification.rk
notification.save.exchange-name=apiclient.save.notification.ex
notification.save.queue-name=apiclient.save.notification.qu

notification.queue-recibir.notification.queue-name=apiclient.recibir.notification.qu
spring.rabbitmq.virtual-host=EL_VHOST_DONDE_LA_CREASTE


notification.delete.routingkey-name=apiclient.delete.notification.rk
notification.delete.exchange-name=apiclient.delete.notification.ex
notification.delete.queue-name=apiclient.delete.notification.qu