products.product.process.routingkey-name-save=apiproducts.process.save.product.rk
products.product.process.exchange-name-save=apiproducts.process.save.product.ex
products.product.queue-name-save=apiproducts.process.save.product.qu

products.product.process.routingkey-name-delete=apiproducts.process.delete.product.rk
products.product.process.exchange-name-delete=apiproducts.process.delete.product.ex
products.product.queue-name-delete=apiproducts.process.delete.product.qu

products.product.process.routingkey-name-update=apiproducts.process.update.product.rk
products.product.process.exchange-name-update=apiproducts.process.update.product.ex
products.product.queue-name-update=apiproducts.update.process.product.qu

products.product.process.routingkey-name-patch=apiproducts.process.patch.product.rk
products.product.process.exchange-name-patch=apiproducts.process.patch.product.ex
products.product.queue-name-patch=apiproducts.process.patch.product.qu


products.campaign.process.routingkey-name-save=apiproducts.process.save.campaign.rk
products.campaign.process.exchange-name-save=apiproducts.process.save.campaign.ex
products.campaign.process.queue-name-save=apiproducts.process.save.campaign.qu

products.campaign.process.routingkey-name-delete=apiproducts.process.delete.campaign.rk
products.campaign.process.exchange-name-delete=apiproducts.process.delete.campaign.ex
products.campaign.process.queue-name-delete=apiproducts.process.delete.campaign.qu

products.campaign.process.routingkey-name-update=apiproducts.process.update.campaign.rk
products.campaign.process.exchange-name-update=apiproducts.process.update.campaign.ex
products.campaign.process.queue-name-update=apiproducts.update.process.campaign.qu


